# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

############################################################################

[package]
name = "test_1"
version = "0.1.0"
edition = "2021"

############################################################################

[dependencies]
# Common dependencies
thiserror = { workspace = true }

# Tokio
tokio = { workspace = true }

# Templates
askama = "^0.12.1"